itk-dev/os2forms_selvbetjening

composer.json, composer.lock, config/sync/core.entity_form_display.user.user.default.yml, config/sync/core.entity_view_display.user.user.default.yml, config/sync/core.extension.yml, config/sync/field.field.user.user.field_az_ident.yml, config/sync/field.field.user.user.field_department.yml, config/sync/field.field.user.user.field_is_leader.yml, config/sync/field.field.user.user.field_name.yml, config/sync/field.storage.user.field_az_ident.yml, config/sync/field.storage.user.field_department.yml, config/sync/field.storage.user.field_is_leader.yml, config/sync/field.storage.user.field_name.yml, config/sync/r4032login.settings.yml, web/modules/custom/itkdev_openid_connect/README.md, web/modules/custom/itkdev_openid_connect/itkdev_openid_connect.module
https://jira.itkdev.dk/browse/DW-400
* Enables os2forms_user_field_lookup module.
* Adds custom user fields.
* Disarms “User default page” rules during OpenID Connect login flow if need be.
=> DW-400: User fields

composer.json, composer.lock, config/sync/openid_connect.settings.yml, web/modules/custom/itkdev_openid_connect/itkdev_openid_connect.module
https://jira.itkdev.dk/browse/DW-400
Fixes handling of redirect during OIDC login.
=> DW-400: Login fixes

web/modules/custom/os2forms_permissions_by_term/os2forms_permissions_by_term.services.yml
https://jira.itkdev.dk/browse/DW-411
- DW-411: Added missing maestro_template_helper service
=> DW-411: maestro_template_helper

config/sync/permissions_by_term.settings.yml
https://jira.itkdev.dk/browse/DW-437
=> DW-437: Changed permission-by-terms settings

config/sync/webform.settings.yml
https://jira.itkdev.dk/browse/DW-437
Change default webform path to include "/"
=> DW-437: Changed default path config

README.md, config/sync/core.extension.yml
https://jira.itkdev.dk/browse/DW-450
Installs the memcache module.
=> DW-450: Installed memcache module

web/modules/custom/os2forms_permissions_by_term/os2forms_permissions_by_term.module, web/modules/custom/os2forms_permissions_by_term/os2forms_permissions_by_term.services.yml, web/modules/custom/os2forms_permissions_by_term/src/Helper/Helper.php, web/modules/custom/os2forms_permissions_by_term/src/Helper/MaestroTemplateHelper.php, web/modules/custom/os2forms_permissions_by_term/src/Routing/RouteSubscriber.php
https://jira.itkdev.dk/browse/DW-452 - Node access for anonymous users based on referenced webform
https://jira.itkdev.dk/browse/DW-453 - Limit webform options and group options on node based on user groups.
https://jira.itkdev.dk/browse/DW-457 - Remove access to submission overview page
https://jira.itkdev.dk/browse/DW-459 - User access control on maestro flows
=> Added changes to os2forms_permissions_by_term

web/modules/custom/os2forms_permissions_by_term/src/Helper/Helper.php
https://jira.itkdev.dk/browse/DW-481
- Changed a default form value to a submit handler
- Moves a bit of code around
- Add a few comments
=> Moved form default value to submission handler, and rearranged a bit

config/sync/advancedqueue.advancedqueue_queue.send_digital_post.yml
Queue for sending digital post
Related to https://github.com/itk-dev/os2forms_digital_post/pull/19
=> DW-532: Added digital post queue

config/sync/user.role.flow_designer.yml, config/sync/user.role.forloeb_designer.yml, config/sync/user.role.medarbejder.yml
- Change medarbejder permissions
- Update config to match drupal version
=> DW-537: Changed permissions

web/modules/custom/os2forms_rest_api/os2forms_rest_api.services.yml, web/modules/custom/os2forms_rest_api/src/WebformHelper.php
https://jira.itkdev.dk/browse/CHAT-16
Adds info on webform API endpoints.
=> Add info on API endpoints

web/modules/custom/os2forms_rest_api/src/WebformHelper.php
https://jira.itkdev.dk/browse/CHAT-16
=> CHAT-16: Fixed handling of preview links

composer.json, composer.lock, config/sync/core.extension.yml
Adds and enables Webform Remote Select module.
=> Added webform_remote_select module

config/sync/rest.resource.entity.file.yml, web/modules/custom/os2forms_rest_api/README.md, web/modules/custom/os2forms_rest_api/os2forms_rest_api.module, web/modules/custom/os2forms_rest_api/os2forms_rest_api.services.yml, web/modules/custom/os2forms_rest_api/src/WebformHelper.php
https://jira.itkdev.dk/browse/TVIST1-21
* Enables api endpoint for files
=> TVIST1: Enable api endpoint for files

README.md
* Adds Maestro module configuration to README
=> Update README with Maestro configuration

composer.json, composer.lock, web/modules/custom/os2forms_get_organized/src/Helper/ArchiveHelper.php, web/modules/custom/os2forms_get_organized/src/Plugin/WebformHandler/GetOrganizedWebformHandler.php
* Adds option to finalize (journalisere) documents archived in GetOrganized
https://jira.itkdev.dk/browse/DW-541
=> DW-541: Add option to get documents finalized in GetOrganized

README.md
Adds a fix for config_entity_revisions_type duplicate entry error while installing profile during inital repo setup
=> config-entity-readme-update

config/sync/core.date_format.short.yml
ticket:SUPPORT-532. Changed format for short date from m/d/Y - H:i to d. F Y
=> SUPP0RT-532-changed-format-of-short-date

composer.json, composer.lock
https://jira.itkdev.dk/browse/DW-560
- DW-560: Updated itk-dev/web_accessibility_statement version constraint
- DW-560: Updated itk-dev/os2forms_digital_post version constraint
- DW-560: Updated itk-dev/os2forms_nemlogin_openid_connect version constraint
- DW-560: Updated itk-dev/os2forms_user_field_lookup version constraint
=> DW-560: Remove dev version constraints

web/modules/custom/os2forms_api_request_handler/src/Plugin/WebformHandler/WebformHandler.php
https://jira.itkdev.dk/browse/SUPP0RT-553
=> SUPP0RT-553: Allowed much longer authorization header values

web/modules/custom/os2forms_api_request_handler/src/Plugin/WebformHandler/WebformHandler.php
https://jira.itkdev.dk/browse/SUPP0RT-557
=> SUPP0RT-557: Allowed much longer API url values

composer.lock, docker-compose.yml
https://jira.itkdev.dk/browse/SUPP0RT-544
Fixes redirect issue with private files (cf. https://www.drupal.org/project/r4032login/issues/3239514)
- SUPP0RT-544: Updated r4032login module
- SUPP0RT-544: Added Xdebug environment variable
=> SUPP0RT-544: Fix private files redirect issue

composer.json, composer.lock
=> Updated os2forms_cpr_lookup

composer.json, composer.lock
https://jira.itkdev.dk/browse/DW-570
=> DW-570: Locked dompdf to version 0.8.5

web/modules/custom/os2forms_rest_api/src/EventSubscriber/WebformSubmissionEventSubscriber.php
https://jira.itkdev.dk/browse/DW-585
* Uses correct managed file type id.
=> DW-585: Use correct element type for managed files

config/sync/webform.settings.yml
https://jira.itkdev.dk/browse/DW-579
* Updates default email body
=> DW-579: Updated default email body

config/sync/webform.settings.yml
https://jira.itkdev.dk/browse/DW-579
* Updates the html default email body.
=> DW-579: Updated default email body html

composer.json, composer.lock, config/sync/core.date_format.html_date.yml, config/sync/core.date_format.html_datetime.yml, config/sync/core.date_format.html_month.yml, config/sync/core.date_format.html_week.yml, config/sync/core.date_format.html_yearless_date.yml, config/sync/core.extension.yml, web/modules/custom/os2forms_selvbetjening/src/Helper/FormHelper.php
https://jira.itkdev.dk/browse/DW-578
* Adds jQuery UI and datepicker to allow the custom property 'date_date_format'.
* Sets default custom property 'date_date_format' for the `Date list` element.
=> Feature/dw 578 add jquery UI and datepicker

composer.json, composer.lock
Fixes issue with patching with a GitHub patch url.
=> Fixed patch url

composer.lock
https://jira.itkdev.dk/browse/SUPP0RT-670
* Bumps `itk-dev/os2forms_cpr_lookup` version
=> SUPP0RT-670: Bump itk-dev/os2forms_cpr_lookup version

config/sync/webform.settings.yml
* Enables Computed Twig element
=> DW: Enabled Computed Twig element

config/sync/user.role.forloeb_designer.yml
https://jira.itkdev.dk/browse/FORMS-627
=> FORMS-627: Added access to form source for forloeb_designer

composer.json, composer.lock, config/sync/core.extension.yml, config/sync/keyboard_shortcuts.settings.yml
https://jira.itkdev.dk/browse/FORMS-636
Adds keyboard shortcuts.
=> FORMS-636: Added keyboard shortcuts

README.md, web/modules/custom/os2forms_selvbetjening/os2forms_selvbetjening.services.yml, web/modules/custom/os2forms_selvbetjening/src/EventSubscriber/ResponseSubscriber.php
Makes it possible to show an admin message.
=> Admin message

config/sync/core.extension.yml
https://jira.itkdev.dk/browse/FORMS-620
=> FORMS-620: Enable os2forms_user_menu module

config/sync/webform.settings.yml
https://jira.itkdev.dk/browse/FORMS-664
Enables “Log all submission events for all webforms” (Home > Administration > Structure > Webforms > Configuration > Submissions).
=> FORMS-664: Enable submission event logging on all forms

composer.json, composer.lock
https://jira.itkdev.dk/browse/FORMS-656
* Adds patch for allowing hiding of sections in emails
https://www.drupal.org/project/webform/issues/3307580
=> F0RMS-656: Added patch allowing hiding of section titles in emails

composer.lock
https://jira.itkdev.dk/browse/FORMS-667
Updates itk-dev/os2forms_nemlogin_openid_connect to [version 1.1.1.](https://github.com/itk-dev/os2forms_nemlogin_openid_connect/releases/tag/1.1.1).
=> FORMS-667: Updated itk-dev/os2forms_nemlogin_openid_connect

CHANGELOG.md
=> Perthaarhus changelog

config/sync/webform.settings.yml
Remove REST and save to file handlers
=> Clean up handlers

web/modules/custom/os2forms_permissions_by_term/src/Helper/MaestroTemplateHelper.php
https://jira.itkdev.dk/browse/FORMS-592
Limit a dropdown in a submit handler
=> FORMS-592: Limit dropdown in maestro submit handler

web/modules/custom/os2forms_permissions_by_term/os2forms_permissions_by_term.services.yml, web/modules/custom/os2forms_permissions_by_term/src/Helper/Helper.php
https://jira.itkdev.dk/browse/FORMS-642
- Always allow node view access if node is tagged with anonymous.
=> Updated node vision

.github/workflows/pr.yaml, CHANGELOG.md
https://jira.itkdev.dk/browse/FORMS-680
=> FORMS-680: Added check for change in CHANGELOG.md in action

CHANGELOG.md, composer.json, composer.lock
Cleans up composer repositories.
=> Cleaned up composer

CHANGELOG.md, composer.lock
https://jira.itkdev.dk/browse/FORMS-709
* Updates to [OS2Forms CPR Lookup 1.7.0](https://github.com/itk-dev/os2forms_cpr_lookup/releases/tag/1.7.0).
* Updates to  [OS2Forms CVR Lookup 1.3.0](https://github.com/itk-dev/os2forms_cvr_lookup/releases/tag/1.3.0).
=> FORMS-709: Updates

CHANGELOG.md, composer.json, composer.lock, config/sync/core.extension.yml
https://jira.itkdev.dk/browse/FORMS-686
Adds the OS2Forms sync module.
=> FORMS-686: Added OS2Forms sync module

CHANGELOG.md, web/modules/custom/os2forms_api_request_handler/src/Plugin/AdvancedQueue/JobType/PostSubmission.php, web/modules/custom/os2forms_api_request_handler/src/Plugin/WebformHandler/WebformHandler.php, web/modules/custom/os2forms_get_organized/src/Plugin/AdvancedQueue/JobType/ArchiveDocument.php, web/modules/custom/os2forms_get_organized/src/Plugin/WebformHandler/GetOrganizedWebformHandler.php
=> Add handler id to webform handlers

CHANGELOG.md, composer.json, composer.lock, config/sync/core.entity_form_display.user.user.default.yml, config/sync/core.entity_view_display.user.user.default.yml, config/sync/core.extension.yml, config/sync/field.field.user.user.field_organisation_user_id.yml, config/sync/field.storage.user.field_organisation_user_id.yml, config/sync/openid_connect.settings.yml
https://jira.itkdev.dk/browse/FORMS-671
* Updates `os2forms/os2forms_organisation` to version `1.0.0`
=> Updated os2forms/os2forms_organisation version

CHANGELOG.md, composer.lock
Update os2forms_failed_jobs module
=> Updated failed jobs module

CHANGELOG.md, composer.json, composer.lock
https://jira.itkdev.dk/browse/FORMS-725
- Update os2forms_webform_submission_log (1.0.0)
=> Updated webform_submission_log moduled

CHANGELOG.md, composer.json, composer.lock
Remove dompdf dependency from os2forms_selvbetjening
=> Updated dompdf

.docker/nginx.conf, .docker/vhost.conf, CHANGELOG.md, docker-compose.dev.yml, docker-compose.redirect.yml, docker-compose.server.override.yml, docker-compose.server.yml, docker-compose.yml
Incorporates latest changes from https://github.com/itk-dev/devops_itkdev-docker/tree/develop/templates/drupal-9 and adds `docker-compose.server.override.yml` for more juice.
=> Update docker compose setup

CHANGELOG.md, config/sync/editor.editor.basic_html.yml, config/sync/editor.editor.full_html.yml, config/sync/webform.settings.yml
https://jira.itkdev.dk/browse/FORMS-727
- Update editor config
- Disable ip tracking by default on webforms
- Change structure of .yml
=> FORMS-727: Disable ip tracking and update .yml format of other entries

CHANGELOG.md, composer.lock
https://jira.itkdev.dk/browse/FORMS-755
=> FORMS-755: Updated os2forms_forloeb and ultimate_cron versions

docker-compose.yml
Added phpfpm container to frontend network to allow it to find another docker compose project nginx
=> BOOKING-68: Added phpfpm container to frontend network

CHANGELOG.md, web/modules/custom/os2forms_permissions_by_term/src/Helper/Helper.php
https://jira.itkdev.dk/browse/FORMS-787
Fixes check for webform groups.
=> FORMS-787: Fixed check for groups

CHANGELOG.md, README.md, config/sync/os2web_datalookup.datafordeler_cvr.yml, config/sync/os2web_datalookup.groups.settings.yml, config/sync/os2web_datalookup.serviceplatformen_cpr_extended.yml
Updates CPR and CVR service config.
=> FORMS-782: Update service config

CHANGELOG.md, config/sync/config_ignore.settings.yml, config/sync/os2web_datalookup.datafordeler_cvr.yml, config/sync/webform.settings.yml
https://jira.itkdev.dk/browse/FORMS-782
Enables CVR elements and work around issue with config not being overridable in `settings.local.php`.
=> FORMS-782: CVR config

CHANGELOG.md, config/sync/block.block.footer.yml, config/sync/block.block.languagedropdownswitcher.yml, config/sync/block.block.os2forms_selvbetjening_theme_page_title.yml, config/sync/block.block.os2forms_selvbetjening_theme_primary_local_tasks.yml, config/sync/block.block.sitebranding.yml, config/sync/block.block.usermenu.yml
=> Moved langauge block

.docker/data/.gitignore, .docker/data/README.md, .docker/vhost.conf, CHANGELOG.md, composer.json, composer.lock
https://jira.itkdev.dk/browse/FORMS-674
=> FORMS-674: Search

CHANGELOG.md, config/sync/user.role.forloeb_designer.yml
https://jira.itkdev.dk/browse/SUPP0RT-986
* Gives `Selvbetjeningsdesigner` permission to translate content (selvbetjeningssider)
=> SUPP0RT-986: Allowed translation of content

CHANGELOG.md, composer.lock
=> Release 2.2.0

CHANGELOG.md, composer.lock
=> Release 2.2.1

CHANGELOG.md, config/sync/core.extension.yml
https://jira.itkdev.dk/browse/FORMS-830
* Enables `Webform Validation` [module](https://www.drupal.org/project/webform_validation)
=> FORMS-830: Enabled Webform Validation module

CHANGELOG.md, web/modules/custom/os2forms_fbs_handler/src/Client/FBS.php, web/modules/custom/os2forms_fbs_handler/src/Client/Model/Patron.php, web/modules/custom/os2forms_fbs_handler/src/Plugin/WebformHandler/FbsWebformHandler.php
Ticket: https://jira.itkdev.dk/browse/SUPP0RT-1041
=> Minor type corrections to FBS handler

CHANGELOG.md, composer.json, composer.lock
https://jira.itkdev.dk/browse/FORMS-836
* Applies patch fixing webform filtering on category.
https://www.drupal.org/project/webform/issues/3313766
=> FORMS-836: Applied patch fixing webform filtering on catogory

CHANGELOG.md, config/sync/views.view.user_admin_people.yml
https://jira.itkdev.dk/browse/FORMS-844
* Updates people filtering to consider user field name.
=> FORMS-844: Configured filtering on users to consider user field name

CHANGELOG.md, composer.lock
https://jira.itkdev.dk/browse/FORMS-847
* Updates to `os2forms/os2forms_sync` 1.1.1
=> FORMS-847: Updated to os2forms/os2forms_sync 1.1.1

CHANGELOG.md, composer.lock
https://jira.itkdev.dk/browse/FORMS-847
* Updates to `os2forms/os2forms_sync` 1.1.2
=> FORMS-847: Updated to os2forms/os2forms_sync 1.1.2

CHANGELOG.md, composer.json, composer.lock
https://jira.itkdev.dk/browse/FORMS-835
* Updates to `itk-dev/os2forms_digital_post` and updates `dompdf/dompdf`
=> FORMS-835: Updated os2forms_digital_post and dompdf

CHANGELOG.md
https://jira.itkdev.dk/browse/FORMS-835
Release 2.3.1
=> Release 2.3.1

CHANGELOG.md, config/sync/core.extension.yml
=> Release 2.4.1

CHANGELOG.md
=> Release 2.4.2

CHANGELOG.md, config/sync/os2forms_selvbetjening_theme.settings.yml
https://jira.itkdev.dk/browse/FORDRIF-149
* Updated Selvbetjening theme favicon
=> FORDRIF-149: Updated selvbetjening theme logo

CHANGELOG.md, config/sync/webform.settings.yml
https://jira.itkdev.dk/browse/SUPP0RT-1153
* Enables `container` element
=> SUPP0RT-1153: Enabled container webform element

CHANGELOG.md, composer.json, composer.lock
https://jira.itkdev.dk/browse/FORDRIF-296
* Downgrades `drupal/leaflet`
=> FORDRIF-296: Downgraded drupal leaflet

CHANGELOG.md, composer.lock
* Updates to `os2forms/os2forms_get_organized` `1.1.4`
* Updates to `os2forms/os2forms_organisation` `1.3.1`
=> Updated OS2Forms GetOrganized and Organisation

CHANGELOG.md
=> FORDRIF-99: Updated changelog

CHANGELOG.md, composer.json, composer.lock, config/sync/core.extension.yml, web/modules/custom/os2forms_permissions_by_term/os2forms_permissions_by_term.module, web/modules/custom/os2forms_permissions_by_term/src/Helper/Helper.php
https://jira.itkdev.dk/browse/FORDRIF-308
* Composer update
* Removes patch (https://www.drupal.org/project/lang_dropdown/issues/3348277)
* Uninstalls admin_audit_trail, os2forms_cpr_lookup and os2forms_cvr_lookup modules.
=> FORDRIF-308: Composer update and removal of patch

CHANGELOG.md, config/sync/advancedqueue.advancedqueue_queue.os2forms_forloeb_notification.yml, config/sync/config_ignore.settings.yml, config/sync/maestro.maestro_queue.token.yml, config/sync/maestro.settings.yml, config/sync/mailsystem.settings.yml
https://jira.itkdev.dk/browse/FORMS-875
Adds missing config for updated os2forms_forloab module.
=> Added missing config

CHANGELOG.md, composer.json, patches/drupal/maestro/maestro_token.patch
https://jira.itkdev.dk/browse/FORDRIF-311
* Patches `queueToken` handling in maestro.
=> Patched maestro token handling

CHANGELOG.md
=> Release 2.6.3

CHANGELOG.md, composer.json, composer.lock
Removed itk-dev/itkdev-booking from composer install since it has been moved to modules/custom
=> BOOKING-285: Removed itk-dev/itkdev-booking

CHANGELOG.md, config/sync/core.menu.static_menu_link_overrides.yml
https://jira.itkdev.dk/browse/FORDRIF-345
* Hides duplicated menu links.
=> FORDRIF-345: Hid duplicated menu links

CHANGELOG.md, README.md, web/themes/custom/os2forms_selvbetjening_theme/assets/logout-suggestion.js, web/themes/custom/os2forms_selvbetjening_theme/os2forms_selvbetjening_theme.libraries.yml, web/themes/custom/os2forms_selvbetjening_theme/os2forms_selvbetjening_theme.theme, web/themes/custom/os2forms_selvbetjening_theme/templates/page/page--4xx.html.twig
https://leantime.itkdev.dk/?tab=ticketdetails#/tickets/showTicket/558
Uses js to add redirection to logout link on 4xx page
=> #558: Use js to fetch 4xx logout url

CHANGELOG.md, README.md, composer.lock, web/themes/custom/os2forms_selvbetjening_theme/assets/logout-suggestion.js, web/themes/custom/os2forms_selvbetjening_theme/os2forms_selvbetjening_theme.libraries.yml, web/themes/custom/os2forms_selvbetjening_theme/os2forms_selvbetjening_theme.theme, web/themes/custom/os2forms_selvbetjening_theme/templates/page/page--4xx.html.twig
Release 2.7.4
* Organisation fixes
* Update Medarbejder auth 4xx logout link
=> Prepared release 2.7.4

CHANGELOG.md, web/modules/custom/os2forms_selvbetjening/os2forms_selvbetjening.services.yml, web/modules/custom/os2forms_selvbetjening/src/Helper/FormHelper.php, web/themes/custom/os2forms_selvbetjening_theme/templates/page/page--4xx.html.twig
https://leantime.itkdev.dk/#/tickets/showTicket/526
* #526: Add logout link to flow page
**Note** that this will result in two translations, but having the extra explanation on the task page makes sense in my opinion.
=> Release 2.7.5

CHANGELOG.md, web/modules/custom/os2forms_user_menu/src/Plugin/Block/UserMenuBlock.php
https://leantime.itkdev.dk/dashboard/home?tab=ticketdetails#/tickets/showTicket/640
* Uses configured `session_type` to generate login and logout urls.
=> #640: Used session type to generate urls

CHANGELOG.md, composer.lock
https://leantime.itkdev.dk/#/tickets/showTicket/871
Release 2.7.8
* Updates to [OS2Forms NemLogin OIDC 2.0.1](https://github.com/itk-dev/os2forms_nemlogin_openid_connect/releases/tag/2.0.1)
=> Release 2.7.8

CHANGELOG.md, config/sync/views.view.brugere_og_id.yml, config/sync/views.view.formularer_og_kategori.yml
https://leantime.itkdev.dk/#/tickets/showTicket/1042
* Adds views exported from production
=> #1042: Added views

CHANGELOG.md, README.md, composer.json, composer.lock, config/sync/core.extension.yml, config/sync/views.view.brugere_og_id.yml, config/sync/views.view.formularer_og_kategori.yml
Release 2.7.9
**Release date will be added before merge**
=> Prepared release branch 2.7.9

.github/workflows/pr.yaml, CHANGELOG.md, docker-compose.override.yml
https://leantime.itkdev.dk/?tab=ticketdetails#/tickets/showTicket/1040
* Fixes asset building by updating docker-compose node setup.
=> #1040: Fixed asset building setup

CHANGELOG.md, composer.lock
https://leantime.itkdev.dk/#/tickets/showTicket/1296
=> 1296: Update os2forms_fasit

CHANGELOG.md, composer.json, composer.lock, config/sync/clamav.settings.yml, config/sync/core.extension.yml, docker-compose.override.yml, docker-compose.server.override.yml
Ticket: https://leantime.itkdev.dk/#/tickets/showTicket/990
=> 990: Added ClamAV to scan files

CHANGELOG.md, composer.lock, web/modules/custom/os2forms_webform_list/src/CustomWebformEntityListBuilder.php
https://leantime.itkdev.dk/#/tickets/showTicket/1300
* Updates `os2forms/os2forms`
* Updates `os2web/os2web_datalookup`
* Updated `drupal/webform`
=> Updated packages

CHANGELOG.md, composer.lock
https://leantime.itkdev.dk/#/tickets/showTicket/1523
* Upgrades https://github.com/itk-dev/getorganized-api-client-php to handle characters not allowed in filenames
=> Upgraded getorganized api client

CHANGELOG.md, config/sync/user.role.flow_designer.yml, config/sync/user.role.forloeb_designer.yml, config/sync/user.role.leder.yml, config/sync/user.role.medarbejder.yml, config/sync/user.role.sagsbehandler.yml, config/sync/user.role.site_admin.yml
https://leantime.itkdev.dk/#/tickets/showTicket/1540
* Updated role permissions with respect to encryption
=> 1540: Updated roles with encryption permission

CHANGELOG.md, web/modules/custom/os2forms_permissions_by_term/os2forms_permissions_by_term.module, web/modules/custom/os2forms_permissions_by_term/src/Helper/Helper.php
https://leantime.itkdev.dk/dashboard/home#/tickets/showTicket/1564
* Updates access check on submissions
=> 1564: Updated access checks

composer.json, composer.lock, config/sync/config_ignore.settings.yml, config/sync/os2forms_encrypt.settings.yml, config/sync/user.role.anonymous.yml
Upgrades to latest `os2forms/os2forms`
=> Upgraded os2forms os2forms

CHANGELOG.md, composer.lock
* Upgrades to https://github.com/itk-dev/os2forms_fasit/releases/tag/1.1.0
=> Upgrade os2forms fasit

CHANGELOG.md, composer.json, composer.lock, patches/drupal/os2forms/hideAdresseBeskyttelseTextOnNemIdCprElements.patch
https://leantime.itkdev.dk/#/tickets/showTicket/2507
* Added patch removing address protection text on CPR elements
=> Added patch removing address protection text on CPR elements

composer.json, composer.lock
https://leantime.itkdev.dk/#/tickets/showTicket/2838
=> #2838: Applied patch to fix ckeditor 5 link balloons

CHANGELOG.md, composer.lock
https://leantime.itkdev.dk/dashboard/home#/tickets/showTicket/2880
Updates Key Vault module so we don't send `GET` requests with a body.
=> Hotfix: Update Key Vault module

CHANGELOG.md, composer.lock, config/sync/config_ignore.settings.yml, config/sync/core.extension.yml, web/modules/custom/os2forms_selvbetjening/src/Commands/LookupCommands.php, web/modules/custom/os2forms_user_menu/src/Plugin/Block/UserMenuBlock.php
https://leantime.itkdev.dk/#/tickets/showTicket/1064
* Audit log v1
* Updates `os2web_audit`
* Updates `os2web_datalookup`
* Updates `os2forms`
* Config ignored `os2web_audit` settings
* Enables `os2web_audit` module
* Enables `os2web_audit_user` module
**Note** that config ignore is now ordered alphabetically upon saving it hence the many changes despite only having added `'os2web_audit.*'`.
=> Prepared audit logging v1

CHANGELOG.md
=> Release 3.1.0

CHANGELOG.md
=> Release 3.1.1

CHANGELOG.md, composer.lock
Updates to latest os2web_datalookup
=> Updated to latest os2web_datalookup

CHANGELOG.md, web/modules/custom/os2forms_fbs_handler/src/Client/FBS.php, web/modules/custom/os2forms_fbs_handler/src/Client/Model/Guardian.php, web/modules/custom/os2forms_fbs_handler/src/Client/Model/Patron.php, web/modules/custom/os2forms_fbs_handler/src/Plugin/AdvancedQueue/JobType/FbsCreateUser.php, web/modules/custom/os2forms_fbs_handler/src/Plugin/WebformHandler/FbsWebformHandler.php
[3088](https://leantime.itkdev.dk/#/tickets/showTicket/3088)
Updated endpoints to use newest operations. Implemented new way of getting patron data, and adjusted formats of data objects.
=> 3088: FBS handler update

CHANGELOG.md, composer.lock
Updates to lates os2forms_get_organized
Audit log!
=> Updated to latest os2form_get_organized

CHANGELOG.md, composer.lock
Upgrades to latest os2forms core
https://github.com/OS2Forms/os2forms/releases/tag/3.20.0
=> Upgraded os2forms core

CHANGELOG.md, composer.lock
Audit logging of authentication via OIDC. https://github.com/itk-dev/os2forms_nemlogin_openid_connect/releases/tag/2.2.0
=> Audit logging of authentication via OIDC

CHANGELOG.md, composer.lock
https://leantime.itkdev.dk/#/tickets/showTicket/3226
Audit logging in os2forms_organisation.
=> Updated os2forms organisation

CHANGELOG.md, composer.lock, config/sync/advancedqueue.advancedqueue_queue.os2web_audit.yml, config/sync/core.extension.yml, config/sync/os2web_audit_entity.settings.yml
https://leantime.itkdev.dk/#/tickets/showTicket/3226
* Upgrades to latest `os2web_audit`
* Adds `os2web_audit` queue config.
=> Audit logging via queue

composer.lock
Upgrades to latest os2forms_payment. 
* Terms and conditions link can now be configured per element with a fallback in `settings.php`.
=> Upgraded to latest os2forms_payment

CHANGELOG.md, composer.lock
Upgrades to latest os2forms core
https://github.com/OS2Forms/os2forms/releases/tag/3.21.0
=> Upgraded to latest os2forms core

CHANGELOG.md, composer.lock
https://leantime.itkdev.dk/#/tickets/showTicket/3472
* Upgrades `Webform Submissions` endpoint via `os2forms_rest_api`
=> Upgraded os2forms_rest_api

CHANGELOG.md
=> Release 3.2.1

CHANGELOG.md
Release 3.2.2
Contains:
* Audit logging queue cleanup
=> Release 3.2.2

CHANGELOG.md, composer.lock
https://leantime.itkdev.dk/#/tickets/showTicket/3182
* Upgrades to latest `os2forms/os2forms_get_organized` https://github.com/OS2Forms/os2forms_get_organized/releases/tag/1.4.0
=> Upgrade os2forms_get_organized

CHANGELOG.md, config/sync/webform.settings.yml
https://leantime.itkdev.dk/#/tickets/showTicket/3501
* Disables `NemID CPR Fetch data`-element.
=> Disabled cpr fetch data element

CHANGELOG.md, composer.lock, config/sync/advancedqueue.advancedqueue_queue.os2forms_fbs_handler.yml
https://leantime.itkdev.dk/#/tickets/showTicket/3519
* Updates to latest `os2forms`
* Handles issue with missing class.
* Configures fbs queue to be handled via daemon.
=> Update fbs handler

CHANGELOG.md, README.md
https://leantime.itkdev.dk/TimeTable/TimeTable?showTicketModal=3743#/tickets/showTicket/3743
Updates site installation instructions.
=> 3743: Updated site installation instructions

CHANGELOG.md
https://leantime.itkdev.dk/tickets/showKanban#/tickets/showTicket/3787
=> Release 3.2.5

CHANGELOG.md, web/modules/custom/os2forms_custom_view_builders/src/CustomViewBuilderWebformSubmission.php, web/themes/custom/os2forms_selvbetjening_theme/templates/webform/table.html.twig
=> Added support for different headers in table display

CHANGELOG.md, config/sync/filter.format.webform.yml
https://leantime.itkdev.dk/#/tickets/showTicket/3742
* Allows tables in `webform` text format.
=> 3742: Add table to webform text format

CHANGELOG.md
=> Release 3.2.6

CHANGELOG.md, web/themes/custom/os2forms_selvbetjening_theme/README.md, web/themes/custom/os2forms_selvbetjening_theme/templates/webform/webform-email-html.html.twig
https://leantime.itkdev.dk/?tab=timesheet#/tickets/showTicket/3742
* Overrides default webform email html template adding styling to tables.
=> 3742: Customized the webform email html template

CHANGELOG.md, composer.lock
https://leantime.itkdev.dk/#/tickets/showTicket/3910
* Upgrade to latest `os2web_audit`
=> 3910: Updated os2web_audit

CHANGELOG.md
=> Release 3.2.7

CHANGELOG.md, composer.lock
https://leantime.itkdev.dk/#/tickets/showTicket/3960
Release 3.2.8
* Upgrade `os2web/os2web_audit`
=> Prepared release 3.2.8

CHANGELOG.md, composer.lock
https://leantime.itkdev.dk/?tab=ticketdetails#/tickets/showTicket/3961
* Updates `os2web/os2web_audit`
* Updates `itk-dev/os2forms_failed_jobs`
=> 3961: Updated os2web_audit and os2forms_failed_jobs

.github/workflows/pr.yaml, CHANGELOG.md, web/modules/custom/os2forms_custom_view_builders/src/CustomViewBuilderWebformSubmission.php, web/themes/custom/os2forms_selvbetjening_theme/assets/pdf.css
https://leantime.itkdev.dk/404/#/tickets/showTicket/3655
- Fix bug where table display mode would break if displaying a table inside.
- Update display of table i html display mode.
=> Changed table display

CHANGELOG.md, config/sync/maestro.settings.yml, phpcs.xml.dist, web/modules/custom/os2forms_email_handler/src/Plugin/WebformHandler/OS2FormsEmailWebformHandler.php, web/modules/custom/os2forms_selvbetjening/os2forms_selvbetjening.services.yml, web/modules/custom/os2forms_selvbetjening/src/Helper/FormHelper.php
Revert [#4239](https://github.com/itk-dev/os2forms_selvbetjening/pull/413)
=> revert-4239: Maestro bycontentfunction function validation

CHANGELOG.md
https://leantime.itkdev.dk/#/tickets/showTicket/4690
Release 4.4.0
=> Release 4.4.0

CHANGELOG.md, web/modules/custom/webform_migrate/README.md, web/modules/custom/webform_migrate/webform_migrate.info.yml
Removes intermediate module introduced when uninstalling it in https://github.com/itk-dev/os2forms_selvbetjening/pull/333.
=> Removed unused module

CHANGELOG.md, composer.json, composer.lock, config/sync/config_ignore.settings.yml, config/sync/core.extension.yml, config/sync/user.role.site_admin.yml
https://leantime.itkdev.dk/#/tickets/showTicket/4890
* Adds `site_status_message` module
* Gives `site_admin` role the permissions needed to configure the module.
=> #4890: Added site_status_message module

CHANGELOG.md
Release 4.6.2
* Task-console forbedringer
*  Tilføjede maestro bycontentfunction validation
* Tilføjede oversætbar bycontentfunction hjælpetekst
* Rettede henvisning til AAK logo i Maestro notifikationstemplate
=> Release 4.6.2
