itk-dev/os2forms_selvbetjening

composer.lock

Upgrades to https://www.drupal.org/project/maestro/releases/3.0.1-rc4

DW-557: Updated drupal/maestro

---

composer.lock

Bumps version of itk-dev/os2forms_cvr_lookup to 1.2.0.
https://github.com/itk-dev/os2forms_cvr_lookup/releases/tag/1.2.0
This allows prepopulation of CVR element.

DW: Update itk-dev/os2forms_cvr_lookup version to 1.2.0

---

config/sync/webform.settings.yml

https://jira.itkdev.dk/browse/DW-579
Makes field descriptions easier to use (and see) by not hiding them in a hover popup.
Before:
After:

DW-579: Disabled description in popups

---

composer.lock

https://jira.itkdev.dk/browse/FORMS-651
Updates `itk-dev/os2forms_cpr_lookup` to version [1.6.8](https://github.com/itk-dev/os2forms_cpr_lookup/releases/tag/1.6.8).

FORMS-651: Update itk-dev/os2forms_cpr_lookup

---

CHANGELOG.md
composer.json
composer.lock

https://jira.itkdev.dk/browse/FORMS-660
Adds a patch on an outdated module: https://www.drupal.org/project/config_entity_revisions/issues/3260602 to resolve the issue shown below. The real solution is to update the module.
```
Notice: Trying to access array offset on value of type null in Drupal\config_entity_revisions\ConfigEntityRevisionsControllerBase->createUpdateRevision() (line 228 of modules/contrib/config_entity_revisions/src/ConfigEntityRevisionsControllerBase.php).
Drupal\config_entity_revisions\ConfigEntityRevisionsControllerBase->createUpdateRevision(Object) (Line: 123)
webform_revisions_webform_update(Object)
call_user_func_array(Object, Array) (Line: 426)
…
```

FORMS-660: Added patch

---

CHANGELOG.md
config/sync/advancedqueue.advancedqueue_queue.os2forms_digital_post.yml
config/sync/advancedqueue.advancedqueue_queue.send_digital_post.yml

Processing digital post queues via Drupal's cron run seems to not be able to handle many posts. Therefore we use “real” cron to process the queues.

Configure digital post queues to be processed via deamon

---

CHANGELOG.md
config/sync/advancedqueue.advancedqueue_queue.get_organized_queue.yml
config/sync/advancedqueue.advancedqueue_queue.os2forms_api_request_handler.yml
config/sync/views.view.maestro_all_flows.yml
config/sync/webform.settings.yml

https://jira.itkdev.dk/browse/FORMS-742
* Enables `Signature` and `Email confirm` elements
* Sorts maestro tasks by id on `/maestro-all-flows`
* Updates GetOrganized and REST API advanced queues to use daemon
The changes to queues mean we have to add our own cronjobs for running the queues. These have been added but commented out for now until needed.

FORMS-742: Update config

---

.gitignore
CHANGELOG.md
config/sync/config_ignore.settings.yml

https://jira.itkdev.dk/browse/FORMS-763
Ignores attachment component settings.
*Note*: 
```yaml
webform.settings:third_party_settings.webform_entity_print.template
os2forms_attachment.os2forms_attachment_component.*
```
should be added on `/admin/config/development/configuration/ignore` before deploying this.

FORMS-763: Ignore attachment component settings

---

CHANGELOG.md
composer.lock

Updates `os2web/os2web_datalookup` (cf. https://github.com/OS2web/os2web_datalookup/compare/1.5.1...1.5.2).

Updated os2web/os2web_datalookup

---

CHANGELOG.md
README.md
composer.lock

https://jira.itkdev.dk/browse/SUPP0RT-963
* Updated `os2forms/os2forms_get_organized` to version 1.1.0

SUPP0RT-963: Bumped os2forms_get_organized version

---

CHANGELOG.md
composer.lock

https://jira.itkdev.dk/browse/SUPP0RT-1066
* Updates `os2forms/os2forms_get_organized` from `1.1.1` to `1.1.2`

SUPP0RT-1066: Update to os2forms GetOrganized to 1.1.2

---

CHANGELOG.md
composer.lock

https://jira.itkdev.dk/browse/FORDRIF-110
* Updates to `os2forms/os2forms_get_organized` 1.1.3

FORDRIF-110: Updated to os2forms_get_organized 1.1.3

---

CHANGELOG.md
composer.lock

https://jira.itkdev.dk/browse/SUPP0RT-1162
* Updated to [itk-dev/beskedfordeler-drupal 1.1.1](https://github.com/itk-dev/beskedfordeler-drupal/releases/tag/1.1.1)

SUPP0RT-1162: Updated beskedfordeler-drupal to avoid spamming error log

---

CHANGELOG.md
config/sync/config_ignore.settings.yml

https://jira.itkdev.dk/browse/FORDRIF-298
* Adds leaflet layers to config ignore
User permission to `site admin` will be handled in a separate PR.

FORDRIF-298: Config ignored drupal leaflet

---

CHANGELOG.md
composer.lock

https://jira.itkdev.dk/browse/FORDRIF-314
* Updates to latest `os2forms_organisation` [1.3.3](https://github.com/itk-dev/os2forms_organisation/releases/tag/1.3.3)

FORDRIF-314: Updated os2forms_organisation

---

CHANGELOG.md
web/themes/custom/os2forms_selvbetjening_theme/os2forms_selvbetjening_theme.theme
web/themes/custom/os2forms_selvbetjening_theme/templates/page/page--4xx.html.twig
web/themes/custom/os2forms_selvbetjening_theme/templates/page/page.html.twig

https://jira.itkdev.dk/browse/SUPP0RT-1356
Der findes template suggestions til 4xx pages med drupal core:
https://www.drupal.org/node/2363987
I første omgang har jeg bare lavet en generel template der fanger alle 4xx kald, men den kan gøres mere specifik.
Det hele er lagt i temaet fornu. Hvis der på et tidspunkt skal til os2, er der muligvis brug for modul med konfiguration etc.

Added 4xx page template with logout link in default theme

---

.github/workflows/pr.yaml
README.md
composer.json
composer.lock
docker-compose.override.yml
docker-compose.server.override.yml

https://leantime.itkdev.dk/tickets/showKanban?search=true&projectId=41&sprint=all#/tickets/showTicket/410
* Reverts organisation upgrade changes made in release branch (https://github.com/itk-dev/os2forms_selvbetjening/pull/259)
`CHANGELOG.md` was not updated with an entry for the `os2forms_organisation` upgrade in the `release/2.7.1`-branch, hence the non-updated changelog.

FORMS-410: Revert organisation upgrade

---

.gitignore
CHANGELOG.md
README.md
config/sync/core.extension.yml
web/modules/custom/os2forms_email/os2forms_email.info.yml
web/modules/custom/os2forms_email/os2forms_email.module
web/modules/custom/os2forms_email/src/Plugin/WebformHandler/OS2FormsEmailWebformHandler.php

https://leantime.itkdev.dk/?tab=ticketdetails#/tickets/showTicket/779
* Overrides default email handler
*  Adds ability to deny emails by supplying a regexp pattern that must match `to_mail`
* Adds ability to send email to webform owner if email is invalid
* Adds entry in 'webform_submission' log (`/admin/structure/webform/manage/{weform_id}/results/log`) if email cannot be send

#779: Added pattern checks and error emails to email handler

---

CHANGELOG.md
composer.json
composer.lock
patches/drupal/maestro/maestro_entity_autocomplete.patch
web/modules/custom/os2forms_selvbetjening/src/Plugin/EntityReferenceSelection/UserByNameSelection.php

https://leantime.itkdev.dk/?tab=ticketdetails#/tickets/showTicket/1044
* Overrides maestro flow user autocomplete to select by name rather than email (which is the username on our User entity)

#1044: Override maestro flow user autocomplete to select by name

---

config/sync/core.extension.yml

Configuration _ultimate_cron.job.dblog_cron_ depends on the _Database Logging_ module that will not be installed after import.

Fix site install

---

CHANGELOG.md
config/sync/advancedqueue.advancedqueue_queue.fasit_queue.yml

https://leantime.itkdev.dk/#/tickets/showTicket/1303
* Adds missing `os2forms_fasit` queue config.

1303: Add missing os2forms_fasit queue config

---

CHANGELOG.md
composer.json
composer.lock
patches/drupal/os2forms/os2forms_hide_additional_settings_page.diff

https://leantime.itkdev.dk/#/tickets/showTicket/1237
* Hides additional os2forms webform settings page
The additional settings page is redundant as all settings within is contained in the general settings page. Furthermore, saving settings on this page may result in unintended setting changes.

1237: Added patch hiding additional os2forms settings page

---

config/sync/config_ignore.settings.yml
config/sync/core.extension.yml
config/sync/encrypt.profile.webform.yml
config/sync/encrypt.settings.yml
config/sync/key.key.webform.yml
config/sync/os2forms_encrypt.settings.yml

* Adds encryption config
On initial import the `webform` key will be created. Then, due to the addition of `key.key.webform.yml` to config ignore it will not be overwritten on subsequent imports.

Added encryption config

---

CHANGELOG.md
config/sync/entity_print.settings.yml
config/sync/os2forms_forloeb.settings.yml
web/sites/default/settings.php
web/themes/custom/os2forms_selvbetjening_theme/README.md
web/themes/custom/os2forms_selvbetjening_theme/assets/pdf.css
web/themes/custom/os2forms_selvbetjening_theme/templates/pdf/os2forms-attachment--webform-submission.html.twig
web/themes/custom/os2forms_selvbetjening_theme/templates/pdf/os2forms-selvbetjening-maestro-notification-pdf-html.html.twig

Moved from https://github.com/itk-dev/os2forms_selvbetjening/pull/291

#1039: Added overwriteables templates for flow pdfs

---

CHANGELOG.md
composer.json
composer.lock
patches/drupal/core/ckeditor_5_link_default_https.patch

https://leantime.itkdev.dk/#/tickets/showTicket/2161
* Sets `https://` as default protocol
If any other protocol is detected (which hopefully never happens) it will not be overwritten. It is also still possible add links relative to site url, `{site_url}/hest` by using `/hest`
This is purely done to help webform editors and is something that has been added to Drupal 11.x (cf. https://www.drupal.org/project/drupal/issues/2893568)

2161: Added patch making https default on CKEditor 5 links

---

CHANGELOG.md
composer.lock

* Upgrade to latest `os2forms/os2forms_organisation` https://github.com/itk-dev/os2forms_organisation/releases/tag/2.0.2

Updated os2forms organisation version

---

CHANGELOG.md
config/sync/filter.format.maestro_notification.yml
config/sync/user.role.flow_designer.yml
config/sync/user.role.sagsbehandler.yml

https://leantime.itkdev.dk/TimeTable/TimeTable?tab=ticketdetails#/tickets/showTicket/2899
`UrlHelper::stripDangerousProtocols` strips all tokens at start of `href` attribute value, i.e. `<a href="[maestro:task-url]">…</a>`  becomes `<a href="task-url]">…</a>`, when filtering HTML. Therefore, we add a custom text format, Maestro-notifikation, that does _not_ filter HTML
See https://www.drupal.org/project/drupal/issues/2372127 for details on the issue.

2899: Added Maestro notificaton filter format

---

CHANGELOG.md
config/sync/editor.editor.webform.yml

[3168](https://leantime.itkdev.dk/?tab=ticketdetails#/tickets/showTicket/3168)
Shows all icons in the ckeditor instead of hiding them in a dropdown.

3168: webform ckeditor toolbar fix

---

CHANGELOG.md
composer.json
composer.lock

Upgrades to `os2forms/os2forms` 3.19
* Removes `os2forms/os2forms_fasit` requirement
* `os2forms_fasit` has been moved to core, since  3.18 (https://github.com/OS2Forms/os2forms/releases/tag/3.18.0)
* Introduces audit logging of
*  Digital post
* Nemid elements

Upgraded os2forms core

---

CHANGELOG.md
composer.json
composer.lock

[3210](https://leantime.itkdev.dk/?tab=ticketdetails#/tickets/showTicket/3210)
- Added patch for issue regarding webform searches containing æøå

#3210: Added patch fixing error regarding æøå in webform searches

---

CHANGELOG.md
config/sync/advancedqueue.advancedqueue_queue.os2web_audit.yml

* Purges successful advanced queue audit log jobs after 7 days. 
**Note:** Cleanup is done every time the queue is processed.
Before:
After:

Purge succesful audit logging jobs

---

CHANGELOG.md
docker-compose.server.override.yml

<https://leantime.itkdev.dk/#/tickets/showTicket/3758>
Increases memory limit due to 
> $ docker compose exec phpfpm vendor/bin/drush --uri=https://selvbetjening.aarhuskommune.dk/ advancedqueue:queue:process get_organized_queue -vvv
>  …
> PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 134217736 bytes) in /app/vendor/itk-dev/getorganized-api-client-php/src/Service/Documents.php on line 205
>  [warning] Drush command terminated abnormally. [13.39 sec, 444.24 MB]

3758: Increased memory limit

---

CHANGELOG.md
web/modules/custom/os2forms_selvbetjening/src/Helper/FormHelper.php

https://leantime.itkdev.dk/#/tickets/showTicket/3915
* Disables the ajax option on webform general settings for non administrators
> [!NOTE]  
Webforms with this already enabled will need to be updated, hence the option remains for administrators. See the specific webforms (3) on the leantime ticket.

3915: Disabled webform ajax options for regular users

---

CHANGELOG.md
config/sync/openid_connect.settings.yml
web/modules/custom/os2forms_selvbetjening/os2forms_selvbetjening.services.yml
web/modules/custom/os2forms_selvbetjening/src/Helper/FormHelper.php
web/modules/custom/os2forms_selvbetjening/src/Routing/RouteSubscriber.php

<https://leantime.itkdev.dk/TimeTable/TimeTable?showTicketModal=4075#/tickets/showTicket/4075>
Disables login form in three steps to allow only login via OIDC:
First, we tell the OpenID Connect module to “Replace” the login form (https://github.com/itk-dev/os2forms_selvbetjening/pull/403/commits/74088c46ef0ea4010059e17372578ae341e37238):
Before:
After:
Then we disable some login routes (https://github.com/itk-dev/os2forms_selvbetjening/pull/403/commits/704c39a861d568d769dc570aea95642646c503b8):
But the login form can still be summoned by adding `showcore` to the URL:
so, finally, we disarm the login form (https://github.com/itk-dev/os2forms_selvbetjening/pull/403/commits/052b7a8de94941c18076d3cb33c251ab7fb707ad):
And then, at the very end, we [update the …

Disable login form

---

CHANGELOG.md
phpcs.xml.dist
web/modules/custom/os2forms_email_handler/src/Plugin/WebformHandler/OS2FormsEmailWebformHandler.php
web/modules/custom/os2forms_selvbetjening/src/Helper/FormHelper.php

Extension of PR [#4239](https://github.com/itk-dev/os2forms_selvbetjening/pull/413)
This PR implements the ```Squiz.Strings.DoubleQuoteUsage.NotRequired``` rule in the phpcs configuration to enforce consistent use of quotation marks across the codebase.

4239-ext: Add phpcs single quotes rule

---

CHANGELOG.md
config/sync/maestro.settings.yml
phpcs.xml.dist
web/modules/custom/os2forms_email_handler/src/Plugin/WebformHandler/OS2FormsEmailWebformHandler.php
web/modules/custom/os2forms_selvbetjening/os2forms_selvbetjening.services.yml
web/modules/custom/os2forms_selvbetjening/src/Helper/FormHelper.php

[#4239](https://leantime.itkdev.dk/#/tickets/showTicket/4239)
Sets out to prevent errors caused by providing invalid number of parameters when configuring a SetProcessVariable task in a Maestro flow.

4239: Maestro bycontentfunction function validation

---

CHANGELOG.md
web/modules/custom/os2forms_queued_email/src/Plugin/AdvancedQueue/JobType/QueuedEmail.php
web/modules/custom/os2forms_queued_email/src/Plugin/Mail/QueuedSmtpPhpMail.php
web/modules/custom/os2forms_queued_email/src/Plugin/WebformElement/Os2FormsManagedFile.php
web/modules/custom/os2forms_queued_email/src/Plugin/WebformElement/Os2FormsQueuedEmailFileTrait.php
web/modules/custom/os2forms_queued_email/src/Plugin/WebformElement/Os2FormsWebformAudioFile.php
web/modules/custom/os2forms_queued_email/src/Plugin/WebformElement/Os2FormsWebformDocumentFile.php
web/modules/custom/os2forms_queued_email/src/Plugin/WebformElement/Os2FormsWebformImageFile.php
web/modules/custom/os2forms_queued_email/src/Plugin/WebformElement/Os2FormsWebformVideoFile.php

https://leantime.itkdev.dk/tickets/showKanban#/tickets/showTicket/4308 
* Hotfixes detection of os2forms attachment elements in queued emails.

Detect os2forms attachment elements corretly in queued emails

---

CHANGELOG.md
composer.lock
web/modules/custom/os2forms_queued_email/src/Plugin/AdvancedQueue/JobType/QueuedEmail.php
web/modules/custom/os2forms_queued_email/src/Plugin/Mail/QueuedSmtpPhpMail.php

https://leantime.itkdev.dk/tickets/showKanban#/tickets/showTicket/4308
* Hotfixes handling of webfoms that do not save submissions.
* Added better error messages.
* Updates [advancedqueue](https://www.drupal.org/project/advancedqueue)

Queued emails: Handle non-submission saving webforms and cleanup

---

CHANGELOG.md
web/modules/custom/os2forms_selvbetjening/os2forms_selvbetjening.module

[#5112](https://leantime.itkdev.dk/?tab=ticketdetails#/tickets/showTicket/5112)
Sets out to enrich the option text of "By function" in maestro's "Define variable"-element options.
Added "Read more: <a href="https://os2forms.os2.eu/variabler-i-flow" target="_blank">https://os2forms.os2.eu/variabler-i-flow</a>"
The text (including link) has been made translatable, so it can be edited by the customer at their will.

5112: Add link to byfunction option
